---
title: "App self reflection"
author: "Joyce Lee"
date: "13/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introducing "COVID-19 in EU"
“[COVID-19 in EU](https://joyce-lee.shinyapps.io/a2-covid19/)” is an interactive web application built with “shiny” package along with other packages - “tidyverse”, “shinyWidgets”, “plotly”, “reactable” and “ggthemes” in R. It delivers the information of Covid-19 conditions across the European Union member countries. The two tabs, “Main” and “About”, displayed on the top of the app provide different aspects of messages to our users.

<p>“Main” consists of one bar graph - “Daily number of confirmed cases and deaths”, one line graph - “Trend of cumulative cases and deaths, according to available data recorded for each country” and a table - “Covid-19 related information recorded on the 5th of each month, from 5th January, 2020 to 5th October, 2020”. The most common feature shared among these two graphs and the table is that they are all user-oriented such that the output will change as users input their interested data.
<br>The title pretty much explains the output of the bar graph. Here, users are able to select their interested date and location(s). This will automatically generate the figures of confirmed cases and deaths in a visual format with x-axis labeling the location, while y-axis provides the measurement of count. Due to the adoption of “plotly” package, users can hover on the bars to see the exact numbers.

<p>Following “daily numbers”, the line graph draws the trend of cumulative cases and deaths numbers. Since the date where the first case or death confirmed varies across different locations, the duration for the trend is not set fixed. Rather, it is adjustable in response to users’ interest. X-axis, “date”, represents the duration and y-axis marks the cases and deaths numbers. Again, with “plotly” package, users can get the exact cases or deaths numbers more specifically by hovering over the lines.

<p>Lastly, the table exhibits the cumulative cases and deaths numbers for each country on the fifth of each month from January 2020 until October 2020, as well as their respective population, life expectancy and case fatality rate. The slider enables users to adjust the duration or the date according to their preferences. The ideal of this table is to invite users to make comparisons between more variables and to explore the variation within the trend. To realise this, some features such as sorting the order of values and the search bar are used from “reactable” package to allow greater manipulation for users.

<p>Comprising three sub-sections, “About” acts as the background of this app. It summarises the purpose, the way the data is used in this app including the data source and the creator.

## Self Review
<h4>What I did well</h4>
*Well-chosen graph types for both graphs.*<br> 
For “Daily number of confirmed cases and deaths”, [grouped bar plot is suitable for visualising the combination of numeric and categorical variables](https://rkabacoff.github.io/datavis/Bivariate.html#bar-chart-on-summary-statistics). On one hand, it presents the amount of cases and deaths numbers in bar length so it becomes easier to compare the difference in between for users. On the other hand, as it is a “grouped” bar plot, greater comparisons can be made among different groups, in this case, it is location.<br>
Characterised by [connecting data points over a time interval](https://www.investopedia.com/terms/l/line-graph.asp), the line graph for “Trend of cumulative cases and deaths, according to available data recorded for each country” is able to portray the change in cases or deaths numbers over a continuous period of time. Users can easily understand the trend with upward and downward sloping patterns.
<p>*Clear user-interface layout.*
<br>With all required inputs from users contained in the sidebar panel on the left, users can intuitively spot the required elements in order to get the graphs and the table work for them. The sufficient spaces between the inputs for each graph and table distinguish the corresponding required inputs for each. Moreover, the labels for each graph explain the meaning of the results well. All in all, this interface is user-friendly with clear presentation.



<h4>What can be improved</h4>
*Label names within legend should be renamed*.<br>
The two colours in the bar graph “Daily number of confirmed cases and deaths”, distinguish the types, which are cases and deaths. Although this message can be found in the legend box, the label names need to be better presented. Instead of naming them as “new_cases” and “new_deaths”, the names should be replaced with something like “Cases” and “Deaths” to refine the overall wording quality and the appearance. 

<p>*Slider scale should be broken down into months rather than date with days.*
<br>As already indicated in the title “Covid-19 related information recorded on the 5th of each month, from 5th January, 2020 to 5th October, 2020”, it is not necessary to have the days to be included. This may bring about confusion for users, so having only months is preferable and clearer. 

<p>*Missing values or data not yet recorded should be symbolised with “NA” or “-”.*
<br>In some locations such as Estonia, the first Covid-19 case was confirmed on 28th February, 2020, meaning 0s are listed in the cells under “Total cases” column on 5th January and 5th February.  Knowing that 0 cannot be divided by 0, the value for “Case fatality rate” is undefined. Yet in this app, these undefined cells for “Case fatality rate” are left blank in the table. To improve the completeness of the table, blank should be replaced with symbols like “-”. This amendment could also enhance the readability for users. 
<br>Sometimes there are missing values for “Total cases” and “Total deaths” due to inconsistent data collected from various organisations. For example, on 5th March, there are missing values for the total number of cases and deaths in Estonia. Nevertheless, these values are shown in blanks, which seems to be ambiguous for users. To fix this issue, “NA” should be placed in cells.



<h4>Plausible addition</h4>
*Comparison between EU member and non-EU member European countries.*
<br>Despite that this app mainly studies the impact of Covid-19 in the EU countries, it would be interesting to make comparisons with that in non-EU European countries. This idea is feasible since the dataset used in this app contains data globally. With different total populations of the EU countries and non-EU European countries, I can take all total cases number divided by total population of all EU countries as a whole, then repeat this process for non-EU European countries. With the two calculated numbers, I can get an overview of, to what extent, people or governments of the EU and non-EU European countries had been preventing themselves from contracting Covid-19. I would present the two figures in two seperate value boxes so users can capture this brief idea in a short time.
<br>Case fatality rate for EU countries and non-EU European countries, as a whole for each might contribute towards the comprehensiveness of the comparison. This can be done by summing up the total deaths numbers of all EU countries, then divided by the summation of total cases number of all EU countries. In the same way, repeat this process for non-EU European countries. The calculated case fatality rates for both enable users to examine whether it is EU countries or non-EU European countries that had been taking better care of the patients with the lower case fatality rate.

*Flag for each location within table.*
<br>I am not able to recognise every EU member country. With this assumption that some users might not be familiar with them all, I would include the flag next to each country name in the cells under “location” column in the table. This is doable with the “reactable” package, which I had used to build the table. To do this, the items that are to be contained within the cells under “location” need to be redefined with a function and then call on “div” with “img” to follow the path where the flag image is saved. This would hopefully “decorate” the appearance, as well as enrich the content of this app.


<h4>Addition not possible due to limitation in data or technology</h4>
*EU map*
<br>An addition I would like to include is a map for all EU countries that reveals the severity of Covid-19 conditions over all EU countries. Ideally, the severity levels can be shown by different dimensions of circles according to the total cases number. Nonetheless, the dataset used does not contain longitude and latitude for all countries which is considered as a limitation in data. 
For now, a possible solution I could think of is to manually search the longitude and latitude for each EU country online, then combine them with the original dataset through web scraping. 

## References
Halton, C. (2019). Line Graph. Retrieved from https://www.investopedia.com/terms/l/line-graph.asp

Kabacoff, R. (2018). *Data Visualization with R (an opensource textbook)*. Retrieved from https://rkabacoff.github.io/datavis/


